# -*- coding: utf-8 -*-
"""Conceitos principais.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1PXFYJWDLyA7nB6Ts6V4rkdbTEnGPettk

*   Declarar variáveis
*   print
*   if-elif\else
*   while
*   for
*   listas
*   dicionário
"""

idade=10
print(f"a idade do meu filho é {idade}")

idade= 9
if idade <10:
  print("meu filho tem menos que 10 anos")
else:
  print("meu filho tem mais que 10 anos")

tempo_de_coleta=10 #segundos
while tempo_de_coleta != 0: #!= significa diferente
  print("coletando")
  tempo_de_coleta -= 1 #mesma coisa que tempo_de_coleta = tempo_de_coleta-1
  print(f"o tempo de coleta restante é {tempo_de_coleta}")
  if tempo_de_coleta ==0 :
    print("coleta finalizada")  #break no final

for i in range(1,11):  #entre os números de 1 e 11-1 (10)
  print (f"Passaram{i} segundos de coleta")

nomes=['ezequiel', 'larissa', 'enzo', 5]
extra='geovana'
print(nomes)
nomes.append(extra)
print(nomes)

lista=[]
Dados_do_paciente =